CREATE TABLE IF NOT EXISTS categories (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 name TEXT NOT NULL UNIQUE,
 active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)),
 created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 name TEXT NOT NULL,
 username TEXT NOT NULL COLLATE NOCASE UNIQUE,
 password_hash TEXT NOT NULL,
 role TEXT NOT NULL CHECK(role IN ('GERENTE','ADMINISTRADOR','CAJERO')),
 manager_pin_hash TEXT,
 active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)),
 created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS products (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 code TEXT NOT NULL COLLATE NOCASE UNIQUE,
 name TEXT NOT NULL,
 description TEXT NOT NULL DEFAULT '',
 price_cents INTEGER NOT NULL CHECK(price_cents >= 0),
 stock INTEGER NOT NULL CHECK(stock >= 0),
 category_id INTEGER NOT NULL REFERENCES categories(id),
 active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)),
 created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sales (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 folio TEXT UNIQUE,
 cashier_id INTEGER NOT NULL REFERENCES users(id),
 created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
 subtotal_cents INTEGER NOT NULL CHECK(subtotal_cents >= 0),
 total_cents INTEGER NOT NULL CHECK(total_cents >= 0),
 status TEXT NOT NULL DEFAULT 'COMPLETADA' CHECK(status IN ('COMPLETADA','CANCELADA'))
);
CREATE INDEX IF NOT EXISTS idx_sales_folio ON sales(folio);

CREATE TABLE IF NOT EXISTS sale_details (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 sale_id INTEGER NOT NULL REFERENCES sales(id),
 product_id INTEGER NOT NULL REFERENCES products(id),
 product_code TEXT NOT NULL,
 product_name TEXT NOT NULL,
 unit_price_cents INTEGER NOT NULL CHECK(unit_price_cents >= 0),
 quantity INTEGER NOT NULL CHECK(quantity > 0),
 subtotal_cents INTEGER NOT NULL CHECK(subtotal_cents >= 0)
);

CREATE TABLE IF NOT EXISTS sale_cancellations (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 sale_id INTEGER NOT NULL UNIQUE REFERENCES sales(id),
 requested_by INTEGER NOT NULL REFERENCES users(id),
 authorized_by INTEGER NOT NULL REFERENCES users(id),
 reason TEXT NOT NULL DEFAULT '',
 created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
